### ISSUE TITLE
Reporter received args are not consistent with documentation

### ISSUE THREAD

**Issue by AlexTes** [af/envalid#10]
Hiya! Thanks for the amazing module!

The documentation states a reporter receives two args, which makes sense to me. In practise however, a reporter receives an object that contains the two named arguments as properties. I went to create a PR but noticed you are consistent and pass an object containing an error object and env object in your test as well. This is probably a doc update, if not, I'm still willing to submit a PR.

In any case, either the module or the documentation should be updated.

Cheers

**Comment by af** [comment]
Thanks for the report! Could you confirm that the commit above looks good?

**Comment by AlexTes** [comment]
Looks good. The way it's now documented works for me.
