### ISSUE TITLE
extend env result out of `cleanEnv`

### ISSUE THREAD

**Issue by gagoar** [af/envalid#120]
Hi! thanks for providing us with this amazing tool.

I'm looking for some guidance when trying to extend the resulting object that comes out of `cleanEnv` method, particularly because we have `staging` as an environment and we will like to have the same capabilities that are automatically provided for `test`, `production` and `development` environments. (ex: isTest, isProduction/isProd, isDevelopment/isDev)

### Some things we have tried

```typescript
const env = envalid.cleanEnv(process.env, {
     PORT: num({ default: DEFAULT_PORT }),
     NODE_ENV: str({default: 'development'}),
});

return {...env, isStaging: env.NODE_ENV === 'staging'};
```
this example will result in loosing all the automatic methods generated like  isProduction/isProd, isDevelopment/isDev

```typescript
const env = envalid.cleanEnv(process.env, {
     PORT: num({ default: DEFAULT_PORT })
});
env.isStaging = env.NODE_ENV === 'staging';

return env;
```
It will fail because the object is read-only (at least in ts).
I can potentially flip the interface to be able to add a property, but it feels against the lib intent. 

Thanks!

**Comment by af** [comment]
This is now possible in the just-released v7.0.0-beta.1– you can use custom "middleware" to implement your own `isStaging` property. Check out https://github.com/af/envalid#custom-middleware-advanced and https://github.com/af/envalid/blob/master/src/middleware.ts#L53, and please let me know if anything is unclear or broken!
