### ISSUE TITLE
types showing `string` for json variable

### ISSUE THREAD

**Issue by veeramarni** [af/envalid#121]
With the latest changes, we seeing types broken for `json` variable as it gives type as  `string` instead of `any`. 

Here I have `REDIS_CLUSTER_URL` as json variable, but type shown as `string` instead. 

![image](https://user-images.githubusercontent.com/3382355/83742642-acb99400-a627-11ea-888b-b71522e21fd2.png)

It was broken in `6.0.2`

**Comment by af** [comment]
Hi, could you share the value for REDIS_CLUSTER_URL in the cleanEnv() call? 

The only recent change that I could think of that might affect this is [this PR](https://github.com/af/envalid/pull/117/files), but you should be able to pass a type param to `json()` to make the parsed json type whatever you wish

**Comment by af** [comment]
Was never able to repro this, and I've verified it works as expected in v7.0.0-beta.2, so closing
