### ISSUE TITLE
Only require dotenv if necessary

### ISSUE THREAD

**Issue by harrim91** [af/envalid#133]
Hey there,

I've recently started using envalid and I think it's great, especially the TypeScript compatibility. So thanks for making it and maintaining it!

Just wanted to raise an issue I've had where my app crashed when I deployed it because of how I'm using dotenv in a way that's incompatible with envalid.

* In my application I've got dotenv as a dev dependency and I handle loading in the env file myself when running my app locally. When calling `envalid.cleanEnv`, I pass `{ dotEnvPath: null }`.
* When I deploy my app, the dev dependencies are pruned, so dotenv gets removed
* When starting the app in production, envalid throws an error: `Error: Cannot find module 'dotenv'`.

I can get around this simply enough - I just put dotenv in my dependencies, not devDependencies. But it would be great if dotenv was only loaded in if you're actually using it. 

I think in `envalid.js` just changing

```js
const parsed = dotenv.parse(dotEnvBuffer)
```

to 

```js
const parsed = require('dotenv').parse(dotEnvBuffer)
```

would do the trick. 

Happy to open a PR for this if you agree it'd be an improvement!

Thanks!

**Comment by af** [comment]
Hi Michael,

Thanks for the suggestion– splitting out all dependencies, including dotenv, is the plan for the next release (v7). Development on it has stalled a bit but I'm planning to pick it up again during the holidays. Would welcome your feedback/help on the [PR](https://github.com/af/envalid/pull/127)!

**Comment by af** [comment]
Fixed in v7 (currently in beta). Try it out with `yarn add envalid@7.0.0-beta.1`

**Comment by harrim91** [comment]
Just tried it out, looks great. Thanks!
