### ISSUE TITLE
v7.0.0 produce undefined when importing

### ISSUE THREAD

**Issue by Gounlaf** [af/envalid#134]
Hi,

I have an issue with the latest version: I'm importing envalid like below, but it produce an `undefined`.

```typescript
import envalid, {json, str, makeValidator, port, num} from 'envalid'
const cleanedEnv: MyType = envalid.cleanEnv(process.env, {
...
}
```

Result:

```
const cleanedEnv = envalid_1.default.cleanEnv(process.env, {
                                                             ^

TypeError: Cannot read property 'cleanEnv' of undefined
```

I'm using Typescript 4.1.3.
I can't (right now) create a minimal example to reproduce the issue. I will be able to do it next week if needed.

**Comment by af** [comment]
Hi, it looks like your code is using a default export, try using cleanEnv from a named export instead, like:

```
import {cleanEnv, json, str, makeValidator, port, num} from 'envalid'
```

**Comment by carlocorradini** [comment]
I think it's best to have *envalid* export as default. 😅

**Comment by Gounlaf** [comment]
> Hi, it looks like your code is using a default export, try using cleanEnv from a named export instead, like:
> 
> ```
> import {cleanEnv, json, str, makeValidator, port, num} from 'envalid'
> ```

It seems to be working that way.

I don't know what the cons/pros of having something exported as default... at least it's working that way

**Comment by af** [comment]
If you want to get default export-like behavior, you can always import and use it as follows:

```
import * as envalid from 'envalid'
const env = envalid.cleanEnv(...)
```

**Comment by carlocorradini** [comment]
@af 

Can we add a default export to index.ts?

I think ```import * as envalid from 'envalid'``` it's a little bit ugly 😥

We can choose to export only the **cleanEnv** function:
```typescript
import envalid, {str, port} from 'envalid';

const env = envalid.cleanEnv(process.env, {
    PORT: port(),
});
```

**OR**

We can choose to export all functions:
```typescript
import envalid from 'envalid';

const env = envalid.cleanEnv(process.env, {
    PORT: envalid.port(),
});
```

Whatever is your opinion, congratulations (and thanks) for *envalid*.

**Comment by kachkaev** [comment]
If you don’t like the look of `import * as envalid from "envalid"`, you can enable `allowSyntheticDefaultImports` and `esModuleInterop` in `tsconfig.json` → `compilerOptions` and thsi should do the job.

**Comment by kachkaev** [comment]
I suggest keeping exports as is, i.e. avoid introducing a default export. Here's why:
https://basarat.gitbook.io/typescript/main-1/defaultisbad

**Comment by af** [comment]
I'm with @kachkaev, the named exports are simpler, and the only argument against using `import * as envalid from 'envalid'` is a subjective aesthetic one. Just updated the readme for additional clarity
