### ISSUE TITLE
Optional variable for development/tests

### ISSUE THREAD

**Issue by matus123** [af/envalid#135]
Hi,

I would like to ask if there is any way i can define optional variable for development, but enforce it for production

```
const envalid = require('envalid');
const { str, cleanEnv } = envalid;

const env = cleanEnv(process.env, {
    PRODUCTION_STRING: str({ devDefault: undefined }),
});

console.log(env.PRODUCTION_STRING);
```

i tried example above... but i receive an error `ReferenceError: [envalid] Env var not found: PRODUCTION_STRING` 

is there any way i could get `PRODUCTION_STRING` with `undefined` value ?

i am using node v14.5.0;

**Comment by af** [comment]
I think the problem is that you're using `undefined` explicitly as a devDefault (we should probably forbid this in our types 🤔 ). If you change devDefault to an empty string I think it should behave like you probably want.

**Comment by matus123** [comment]
If i dont explicitly set value to `undefined` for `devDefault` property, i am getting error that `PRODUCTION_STRING` is missing.

With empty string it works... but it is not what i am expecting, i am passing these envs to some 3rd party libs and they expect either string or undefined... and i guess empty string might cause issues in some of them.

Currently i am wrapping optional variable retrieval with custom function, which feels really hacky
```
export function optionalEnv(key: keyof typeof env): string | undefined {
    try {
        return env[key] as string;
    } catch (err) {
        const regex = /^ReferenceError: \[envalid\] Env var not found: .*$/;
        const msg: string = err.toString();
        if (regex.test(msg)) {
            return undefined;
        }
        throw err;
    }
}
```
