### ISSUE TITLE
dotEnvPath missing

### ISSUE THREAD

**Issue by jpmayorga** [af/envalid#136]
CleanOptions had a parameter called `dotEnvPath` and in the `envalid@7.0.0` is missing.

What is the config to add  `dotEnvPath` ?

example:
![image](https://user-images.githubusercontent.com/2263749/107813900-0a69b880-6d3f-11eb-806c-5494afb71d5b.png)

**Comment by af** [comment]
As of v7.0, envalid no longer ships with dotenv included. In your case I think adding the following before line 6 should allow your code to work as before (after you install `dotenv` in your project):

```
require('dotenv').config({ path: YOUR_RESOLVED_PATH_HERE })
```
