### ISSUE TITLE
TypeScript issues in v7.0.0

### ISSUE THREAD

**Issue by kachkaev** [af/envalid#137]
After upgrading to envalid v7 and running `yarn lint:tsc`, I encountered these new TypeScript errors in `node_modules/envalid/src/reporter.ts`:

> <img width="969" alt="Screenshot 2021-02-14 at 14 49 11" src="https://user-images.githubusercontent.com/608862/107879995-04591080-6ed4-11eb-838f-a69d27b087cb.png">

What’s probably happening here is my local ts config is being more strict that the one in `envalid` itself. Manually replacing 

```ts
  const missingVarsOutput = []
  const invalidVarsOutput = []
```

with

```ts
  const missingVarsOutput: string[] = []
  const invalidVarsOutput: string[] = []
```

helps.

> <img width="776" alt="Screenshot 2021-02-14 at 14 53 13" src="https://user-images.githubusercontent.com/608862/107880079-79c4e100-6ed4-11eb-94e2-e5f3ff52117a.png">

I’ll revert for v6 for now, but I’m really excited about the changes that v7 has brought! Thanks for your continuous work on this library @af! 🙌

**Comment by af** [comment]
@kachkaev Thanks for the feedback! 

Yes those arrays are being inferred as `any[]`, I'm not sure why since strict mode (and by extension `noImplicitAny`) is on 🤔. I just pushed a commit to `main` to address this, could you give it a spin and let me know if there's still an error? Also if possible could you paste the compilerOptions in your tsconfig? I'm wondering what the difference in config is that catches this.

Closing this issue proactively, but please reopen if you still have errors.

**Comment by kachkaev** [comment]
Thanks for looking into this @af! I'm going to try out the new version in a few days, but your [commit](https://github.com/af/envalid/commit/a694876d3fe5f8a8316d15ce4e26e895f41966f6) makes sense.

My tsconfig:

```json
{
  "compilerOptions": {
    "allowJs": true,
    "downlevelIteration": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": true,
    "lib": ["dom", "dom.iterable", "esnext"],
    "module": "commonjs",
    "moduleResolution": "node",
    "noEmit": true,
    "noImplicitAny": false,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "strict": true,
    "noUncheckedIndexedAccess": true,
    "target": "es5"
  },
  "include": ["**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
```

**Comment by af** [comment]
Thanks! I noticed the typescript version installed via tsdx is still 3.x for me locally. I wonder if that's part of the problem; I can't see any difference in the `compilerOptions` that could explain the discrepancy

**Comment by kachkaev** [comment]
What are your plans or releasing the patch (a694876d3fe5f8a8316d15ce4e26e895f41966f6)? Looks like 7.0.x is still incompatible with TS 4.1.

**Comment by af** [comment]
@kachkaev Ah sorry, I was waiting to hear back from you. Can you confirm that it resolves your issue? If so, I'll release it as 7.0.1

**Comment by kachkaev** [comment]
After a new round of checks, I noticed another key factor to my crash, so sorry for not sharing the full picture earlier. It turns out that I had this import statement in my codebase:

```ts
import defaultReporter from "envalid/src/reporter";
```

It worked well in v6 because files in `src` were consumable by Node directly, but obviously failed in v7 because of the migration to TS. So the reason why my strict TS instance got triggered was because lines like `const missingVarsOutput = []` were present in `src/reporter.ts`, but not in `dist/reporter.d.ts`. The latter file is autogenerated at buildtime and looks quite minimalistic:

```ts
import { ReporterOptions } from './types';
declare const defaultReporter: ({ errors }: ReporterOptions<any>) => void;
export default defaultReporter;
```

After removing `import defaultReporter from "envalid/src/reporter"`, all worked in 7.0.0! Still the tweak you've made in a694876d3fe5f8a8316d15ce4e26e895f41966f6 is a good one as it will allow you to switch to an even stricter TS mode in the future if you want to 👍

**Comment by kachkaev** [comment]
Having removed `defaultReporter` import, I faced a need to copy-paste it into my codebase. I wonder if it would be possible to consume something like `import { defaultReporter } from "envalid"` as a small convenience thing.

In my case, I feel lazy writing a reporter from scratch so what I do is patching the existing one – see example in https://github.com/kachkaev/tooling-for-how-old-is-this-house/commit/b723614f0791db98ce2d17c979d9613e36e13002. Given that patching the whole `defaultReporter` is a bit hacky, perhaps, `envalid` could even expose building blocks of the default reporter to help devs compose them together without writing or pasting too much code? Happy to continue the discussion in a new issue if you prefer.

Thanks again for the lib! It’s one of my favourite little tools that makes Node.js dev a pleasure!

**Comment by af** [comment]
@kachkaev I'm ok with exporting the defaultReporter, I can see that being useful and it doesn't expose too much in the way of implementation details. Maybe there are composable reporting pieces that we could pull out of there later (or parameterization), but I can't think of them at the moment. Would #140 improve the situation on your end?

> Thanks again for the lib! It’s one of my favourite little tools that makes Node.js dev a pleasure! 🖤

Thank you! I really appreciate that :)
