### ISSUE TITLE
[Feature request] add isCI in the same way as isProduction

### ISSUE THREAD

**Issue by leosuncin** [af/envalid#144]
Provide a shorcut to detect when `CI=true` is set, like isProduction

**Comment by af** [comment]
I don't think this belongs in the library itself, but with v7's customizable middleware, you should be able to easily add this yourself by creating a customized version of [the accessor middleware](https://github.com/af/envalid/blob/main/src/middleware.ts#L53) and passing it in to cleanEnv()
