### ISSUE TITLE
default: undefined and devDefault cause "Env var not found: "

### ISSUE THREAD

**Issue by carlocorradini** [af/envalid#149]
I have an env variable that the default value is set to *undefined* and the devDefault is set to a hardcoded value.

Example:

```typescript
cleanEnv(process.env, {
  EXAMPLE_ENV: url({ default: undefined, devDefault: 'https://google.com'}),
});
```

When running in development all works and the value is correctly set to the devDefault.
However, when running in production an error is thrown: ```ReferenceError: [envalid] Env var not found: EXAMPLE_ENV```.
I think that mixing default undefined and devDefault is causing this.

**Comment by af** [comment]
I can not reproduce this using the latest (v7.3.0) version. Quite possible it was fixed along with #138

Please re-open if you're still seeing this
