### ISSUE TITLE
please add `$typeof` as exception in strict check

### ISSUE THREAD

**Issue by veeramarni** [af/envalid#150]
When using in `react-native` with expo. We getting the following error. 

[envalid] Env var not found: $$typeof

The workaround is by adding `$typeof` to `env` file that we pass to envalid. 

Env file
--
```
const env = {
    DOMAIN: 'test',
   MOBILE_CLIENT_ID: '112321',
    // '$typeof': 'null', // Uncomment for workaround to fix the issue
};

const isBrowser = typeof window !== 'undefined';

export default env;

if (isBrowser) {
    // process.env = env;
    process.APP_ENV = env;
}
```

Config.js file
```
import * as envalid from 'envalid';
const { str, num } = envalid;
const env = process['APP_ENV'] || process.env;

export const config = envalid.cleanEnv(env, {
  DOMAIN: str(),
  MOBILE_CLIENT_ID: str(),
});

```

Error
---

```
ReferenceError: [envalid] Env var not found: $$typeof
at /Users/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at /Users/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
at /Users/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at /Users/node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:9:32 in ErrorUtils.setGlobalHandler$argument_0
at [native code]:null in flushedQueue
at [native code]:null in invokeCallbackAndReturnFlushedQueue

```

**Comment by af** [comment]
I don't think it makes sense to bake this exception into the library. I'd recommend trying to use/pass in a forked version of the [proxy middleware](https://github.com/af/envalid/blob/main/src/middleware.ts#L3) that handles this case for you

**Comment by SimenB** [comment]
we could add ability to plug in more into our own so the user can just do `const proxyMiddleware = createProxyWithExtra('$$typeof')` and pass that to `envalid` or something like that

**Comment by veeramarni** [comment]
It would be better to have this feature provided within the package instead of forking it.

**Comment by SimenB** [comment]
To be clear, I don't think we should exclude `$$typeof` by _default_, but I do think it makes sense to expose some utility making it easier to filter out for consumers without completely forking or reimplementing the entire `Proxy`

**Comment by af** [comment]
This might be worth revisiting; it looks like react-refresh checks this $$typeof property to test whether an export is a React component or not (I just ran into it while using envalid in a Nextjs app). Given React's popularity and that we already have exceptions baked in for Jest, I now think it's a reasonable thing to add– though making the exceptions extensible is still also a good idea

**Comment by veeramarni** [comment]
So when this will be fixed, if you plan to fix it?

**Comment by af** [comment]
Just published envalid@7.2.0-beta.1, which has this fixed. Let me know if you still run into issues!

**Comment by mario-petrovic** [comment]
Hey.

Is there any hint on when will this be part of the regular versioning?

Btw, thanks for the quick fix. I started using it recently and got into this wall. Keep up the good work.

**Comment by af** [comment]
That beta release changes how the package is built (via tsc rather than rollup/babel) so I'd prefer to have more folks kick the tires for a little bit before the next "official" release

**Comment by veeramarni** [comment]
I will check today and let you know.

**Comment by veeramarni** [comment]
@af I did a quick test, it is working for me without this error.
