### ISSUE TITLE
comment after var assignment deemed invalid

### ISSUE THREAD

**Issue by Morriz** [af/envalid#153]
This is valid but invalid does not like it:
```bash
SOME_VAR=true # bla
```

It sources fine, it's just that invalid does not trim comments before parsing I guess.

**Comment by af** [comment]
Could you share how you're passing the env vars in to envalid itself? This seems like it's probably more of an issue with dotenv, if you're using it. Usually envalid either receives the output of dotenv, or process.env directly

**Comment by Morriz** [comment]
I see. I will take it to the dotenv repo then.
