### ISSUE TITLE
Env var not found: toJSON

### ISSUE THREAD

**Issue by K41eb** [af/envalid#157]
"envalid": "7.1.0"

I am simply trying to serialize the return value of envalid with `JSON.stringify` but I get `[envalid] Env var not found: toJSON`, probably because of the Proxy: https://github.com/af/envalid/blob/012fa032132f5e2f4a07b8cf41e3c8cfcd019472/src/middleware.ts#L3-51

Would it be possible to add support for it? I don't want to have to write a mapping object for every single variable I parsed:
```js
const config = envalid.cleanEnv<Type>(process.env, validators, options);
JSON.stringify({
  a: config.a,
  b: config.b,
  c: config.c,
  ...
});
```

**Comment by af** [comment]
Good find, could you try https://github.com/af/envalid/pull/158 and let me know if it fixes the issue for you?

**Comment by K41eb** [comment]
It does, thank you very much.
