### ISSUE TITLE
feature: fail at build time when requirements are not met

### ISSUE THREAD

**Issue by tafelnl** [af/envalid#166]
Would it be possible to throw an error at build time when requirements are not met?

**Comment by af** [comment]
Hi, this is not possible because the validation depends on the runtime environment variables. You can, however get failures at build-time using TypeScript if your code tries to access a property on the validated environment object that's not in the validation

**Comment by SimenB** [comment]
`ts-node` is not build time, that's running the code

**Comment by jacobgoh101** [comment]
my bad for being unclear.

This is what I did

```sh
npx ts-node environment.config.ts && npm run build
```
