### ISSUE TITLE
tslib is a runtime dependency

### ISSUE THREAD

**Issue by stalet** [af/envalid#167]
After version 7.2.0 we are getting an error running projects with envalid:

    Error: Cannot find module 'tslib'

Seems that there is a runtime dependency to this package - and it should therefor be added as a dependency - not a devDependency.

**Comment by Dunky13** [comment]
Facing the same issue.

**Comment by af** [comment]
Apologies, looks like tslib was a dep in my other project so I didn't see this. Just published 7.2.1 which should resolve this, let me know if not!

**Comment by stalet** [comment]
Works perfectly!
