### ISSUE TITLE
ts-expect-error problem with 7.2.1

### ISSUE THREAD

**Issue by jefbarn** [af/envalid#169]
node_modules/envalid/src/validators.ts:108:7 - error TS2578: Unused '@ts-expect-error' directive.

108       // @ts-expect-error TS doesn't acknowledge this API by default yet
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

No problem on 7.1.1

**Comment by af** [comment]
Hi, which version of TypeScript are you using?

**Comment by af** [comment]
Follow up question– do you have `@types/node` installed, and if so which version?

**Comment by jefbarn** [comment]
"@types/node": "^14.17.9",
"typescript": "4.3.5"

**Comment by jefbarn** [comment]
So, turns out my IDE automatically imported directly from the 'src' directory and that was causing typescript to try and recompile it.
``` import { port } from 'envalid/src/validators' ```

Removing that resolved the issue.
