### ISSUE TITLE
How to access desc

### ISSUE THREAD

**Issue by ArnabXD** [af/envalid#178]
How do I access the `desc` property of the environment variable?

**Context:** _I want to automate the documentation of my project._

**Comment by af** [comment]
Ha, I kind of forget about `desc`... there's no way to access it on the output– if you want to, it'd probably be best to export your spec object from the same module where you call `cleanEnv`, and then use that to help generate the docs. Hope that helps!

**Comment by ArnabXD** [comment]
I tried that but I couldn't make typescript happy. Can you provide an example with typescript.
