### ISSUE TITLE
Problems with Node 4.3.2

### ISSUE THREAD

**Issue by rastkojokic** [af/envalid#18]
When using the package with node 4.3.2 requiring 'envalid' module produces the following syntax error:

```
{
  "errorMessage": "Unexpected token {",
  "errorType": "SyntaxError",
  ...
}
```

I haven't seen any mentions in Readme about this limitation so is this on purpose?

**Comment by af** [comment]
Hi @rastkojokic, sorry about this, envalid uses ES6 features that are only available in v6 and above. I thought this was mentioned in the readme but I now see that it's not! I'll add a note about that, sorry about wasting your time if you can't upgrade!

**Comment by rastkojokic** [comment]
@af No problems! I'm using AWS lambda and latest Node they support is 4.3.2. That's the reason why I cannot upgrade. But, I was able to downgrade envalid to 1.0.0, change the syntax a bit and it's all good now!

**Comment by af** [comment]
Oh great, glad to hear it! v1 is quite different but I'm glad to hear it's still useful for you
