### ISSUE TITLE
Feature idea: `example` and `docs` fields for validators

### ISSUE THREAD

**Issue by af** [af/envalid#19]
I find that my descriptions for env vars often contain example values, or links to web pages that contain more context. For example:

```js
SENTRY_DSN: str({ desc: 'DSN for sentry. eg. "my.fake.value" See http://foo.com/bar' })
```

Maybe it makes sense to create new fields so these semantics can be captured and dealt with more intelligently by the formatter(s). So that previous example could be:

```js
SENTRY_DSN: str({ desc: 'DSN for sentry', example: 'my.fake.value', reference: 'http://foo.com/bar' })
```

Do you think this would be useful? cc @SimenB

**Comment by SimenB** [comment]
We have `default`s for every variable (at least `devDefault`s), so we have examples from there. What is a reference for?

**Comment by af** [comment]
Ah yes if you have a `default` for everything, then an `example` would not be useful. 

The idea with `reference` is it's a link to documentation or context about the setting (the name of this option could probably be improved!)

**Comment by SimenB** [comment]
Calling it `docs` makes more sense then, IMO. I can see the use case for that, even though I don't think we'll use it (OTTOMH). We map some variables that are injected into the docker containers by k8s, might be useful pointing to some docs for that, I suppose.

So yeah, 👍 from me!

**Comment by af** [comment]
Nice, I like `docs` better as well. Will try and land this soon
