### ISSUE TITLE
envalid in react-native for preview  crashes without giving description of missing env

### ISSUE THREAD

**Issue by veeramarni** [af/envalid#195]
When using with react-native, f the env that need to be passed were missed, we don't get any log or way of know which env it is missing as the app crashes right after it opens. 

Is there a way to show the env values it is missing before it crashes?

**Comment by af** [comment]
You should be able to customize this behavior by customizing the reporter that envalid uses. You can pass in a custom reporter and even re-use the `defaultReporter` with your own custom logic injected

**Comment by veeramarni** [comment]
Sure will go with a custom solution.
