### ISSUE TITLE
testOnly setting variable to Symbol instead of failing

### ISSUE THREAD

**Issue by edosrecki** [af/envalid#197]
Hi.

When using `devDefault: testOnly('value')`, if the environment variable is not set and the NODE_ENV is not `test`, `envalid` will set the value to `testOnlySymbol` and continue executing the program normally. Instead it should exit the program with the error saying that the environment variable is missing.

I found the culprit in your code.

Dev defaut value is set at this line: https://github.com/af/envalid/blob/main/src/core.ts#L76 and then `continue` is called, which effectively skips the `isTestOnlySymbol` check at this line: https://github.com/af/envalid/blob/main/src/core.ts#L86.

Instead `isTestOnlySymbol` check should be moved up, after the dev default value is set.

**Comment by edosrecki** [comment]
Sorry, I wasn't fully clear, if NODE_ENV is not `test` or `production`, `envalid` will set value to `testOnlySymbol` and proceed normally.

I believe that the tests that you linked should be modified to this:
```ts
process.env.NODE_ENV = 'production'
expect(() => cleanEnv({ NODE_ENV: 'production' }, makeSpec(), makeSilent)).toThrow()

process.env.NODE_ENV = 'development'
// THIS DOESN'T HOLD ANYMORE
expect(() => cleanEnv({ NODE_ENV: 'development' }, makeSpec(), makeSilent)).toThrow() 
process.env.NODE_ENV = processEnv
```

**Comment by edosrecki** [comment]
@af did you have time to look into this?

**Comment by af** [comment]
@edosrecki Finally did, sorry about the delay! You were right, there was a bug. Could you check out https://github.com/af/envalid/pull/200 and let me know if it works correctly for you now?

**Comment by edosrecki** [comment]
@af Looks good thanks!
