### ISSUE TITLE
Set defaults during validation

### ISSUE THREAD

**Issue by nicwaller** [af/envalid#2]
I like this module, but there's one thing that could be improved.

It would be great to have a `defaults` key as part of the environment variable specifications that applies a default when the environment variable is undefined. (Clearly this would be exclusive with `required: true`.)

Sure it's possible to provide a default value when calling `envalid.get()` but that quickly leads to repetition of the default value if it is referenced in several places.

I thought I could work around this by implementing a parse function which returns a default value if the variable is undefined, until I realized that `.get()` only works for environment variables that exist, so the parse function never gets called.

**Comment by af** [comment]
Hi Nic,

Definitely agree that would be a nice addition. Actually I've been thinking of overhauling the API (maybe using ES5 properties), and supporting `default` should definitely be a part of that.

**Comment by af** [comment]
@nicwaller give latest master a try, a `default` key is now supported (rest of the API is the same for now)
