### ISSUE TITLE
Require environment variables only if `NODE_ENV` is not set to `test`

### ISSUE THREAD

**Issue by willpinha** [af/envalid#204]
How can I require environment variables with `cleanEnv` only if `NODE_ENV` is not set to `test`?

For example, for the following code:

```js
import { str, host, port } from "envalid";

const specs = {
    NODE_ENV: str({ choices: ["development", "production", "test"] }),

    PG_HOSTNAME: host({ devDefault: "localhost" }),
    PG_PORT: port({ default: 5432 }),
    PG_USERNAME: str(),
    PG_PASSWORD: str(),
    PG_NAME: str(),

    SERVER_PORT: port({ devDefault: 3000 }),
};
```

If `NODE_ENV` is set to `test`, then all PostgreSQL settings are not required, since I am using SQLite for tests

**Comment by af** [comment]
Hi @willpinha, I think [the testOnly option](https://github.com/af/envalid#testonly) would work for this use case, have you tried that?

**Comment by willpinha** [comment]
I wasn't aware of `testOnly`, thanks!
