### ISSUE TITLE
Prevent process exit during tests

### ISSUE THREAD

**Issue by stefee** [af/envalid#210]
I'd like to prevent `envalid.cleanEnv` from exiting the process during tests, but preferably would not have to write my own reporter function to do this as this:
1. Introduces additional logic and cognitive overhead in my codebase
2. Reduces code coverage

Current implementation with `reporter` workaround:

```ts
// ServerContext.ts
export class ServerContext {
  readonly env: ServerCleanEnv;

  private cleanEnv(processEnv: unknown) {
    return envalid.cleanEnv(processEnv, envSpec, {
      // Prevent process exit on error during test
      reporter:
        process.env.NODE_ENV === "test"
          ? ({ errors }) => Object.keys(errors).length && console.error(errors)
          : undefined,
    });
  }

  constructor(processEnv: typeof process.env) {
    this.env = this.cleanEnv(processEnv);
  }
}
```

```ts
// MockServerContext.ts
export class MockServerContext extends ServerContext {
  constructor(env: Partial<ServerEnv> = {}) {
    super({ NODE_ENV: "test", ...mockEnv, ...env }, false);
  }
}
```

```ts
// NodeServerContext.ts
export class NodeServerContext extends ServerContext {
  constructor() {
    super(process.env, true);
  }
}
```

**Comment by af** [comment]
Hi, the proper place to do this is with a reporter, and in your example the extra logic is IMO very minimal to conditionally create a simple reporter that doesn't call process.exit. So I don't think it makes sense to add extra logic for this case when the customization already available is IMO quite reasonable
