### ISSUE TITLE
makeExactValidator is not exported

### ISSUE THREAD

**Issue by ps2goat** [af/envalid#212]
I'm using TypeScript and trying to make a custom validator. Based on the README file, I should have both `makeValidator` and `makeExactValidator` available to me, but `makeExactValidator` cannot be found.

<img width="852" alt="image" src="https://github.com/af/envalid/assets/5384732/2c6c840f-5a08-4ff2-944d-3a10385337a7">
I've tried with 7.3.x and 7.1.x, and neither have `makeExactValidator` exported. When I jumped to the module definition, the two functions are not exported/declared in the index file like the project code suggests, and there's no `./makers` folder either.

The `makeValidator` appears to be exported from `dist/validators.d.ts`

**Comment by af** [comment]
Hi, sorry about this, I believe makeExactValidator was only added in v8, which is still in beta (I should really cut an official release soon though). Try installing `8.0.0-beta.2` and it should be available
