### ISSUE TITLE
How to see description and help for optional env?

### ISSUE THREAD

**Issue by FreePhoenix888** [af/envalid#219]
Imagine I have such env configuration:
```ts
const env = cleanEnv(process.env, {
  GRAPHQL_PATH: str({ desc: 'Path to GraphQL endpoint' }),
  SSL: bool({
    desc: 'Should use SSL',
    default: true,
  }),
  HTML_FILE_NAME: str({
    desc: "Html file name. Pass if you need to test specific file",
    default: "",
    example: "102041891.html"
  })
});
```
How can a user find see doc and descirption for HTML_FILE_NAME ?

**Comment by af** [comment]
`desc` and `example` are mainly intended for the error message when the value is missing or invalid. So in this case:

```ts
cleanEnv({
  SOME_KEY: envalid.json({ desc: 'this is a description', example: 'example val' }),
})
```

If this key is missing you'll get: 

<img width="571" alt="Screenshot 2024-03-16 at 09 27 03" src="https://github.com/af/envalid/assets/25241/b191a069-046d-4d8a-b624-6eb86150f3bc">

That said, you could surface this information in other ways in your app, but it's mostly intended for helpful error messages. Hope that makes sense!

**Comment by FreePhoenix888** [comment]
> `desc` and `example` are mainly intended for the error message when the value is missing or invalid. So in this case:
> 
> ```ts
> cleanEnv({
>   SOME_KEY: envalid.json({ desc: 'this is a description', example: 'example val' }),
> })
> ```
> 
> If this key is missing you'll get:
> 
> <img alt="Screenshot 2024-03-16 at 09 27 03" width="571" src="https://private-user-images.githubusercontent.com/25241/313417407-b191a069-046d-4d8a-b624-6eb86150f3bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NTIxOTAsIm5iZiI6MTcxMDY1MTg5MCwicGF0aCI6Ii8yNTI0MS8zMTM0MTc0MDctYjE5MWEwNjktMDQ2ZC00ZDhhLWI2MjQtNmViODYxNTBmM2JjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDA1MDQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlYTYyNzQxOTVlZDEwZjBmZTMyODBjMjlhOGQ5NTM3YWE2MzZmMzAxYjlmYzFiMmYwZmI1NTNhYWZhYzNiYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kUag4W7D9ukJV4SYHx2oHnRJDdQom0ro5zhU_DzjgOQ">
> That said, you could surface this information in other ways in your app, but it's mostly intended for helpful error messages. Hope that makes sense!

So desc and example for an env that has default value (optional env) is useless?

**Comment by af** [comment]
Yeah they are kind of useless in that case currently, unless you expose them in some other way.

One change we could make is to include the desc/example values in the error message when an invalid value is passed in as well, then they'd still be useful if there was a default value and an invalid runtime env var

**Comment by FreePhoenix888** [comment]
> Yeah they are kind of useless in that case currently, unless you expose them in some other way.
> 
> One change we could make is to include the desc/example values in the error message when an invalid value is passed in as well, then they'd still be useful if there was a default value and an invalid runtime env var

I currently use envs the same way as nextjs do

You have .env as template where envs are specified without specific values
And if you want to use it you should create .env.local

But in this case I need to write there whether an env is optional or not. It would be incredible if we do not need to repeat the same description and info whether env is optional in two places: env files itself, code where envalid is used

Also when people do not have such .env templates the current behavior is uncomfortable, you pass one variable and see that another is required, you pass it and now another variable is required. It would be good to see all the envs that are not passed and should be passed!

Thank you for this library anyway, it helps a lot anyway!
