### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by grempe** [af/envalid#40]
The latest release on the Github releases tab is 3.0.0, but on npm v3.1.0 has been published.

Is it possible to update and cut a new release?

I am especially interested in the following commit as it was throwing warnings when we used it with the [pkg](https://github.com/zeit/pkg) tool:

https://github.com/af/envalid/commit/3a5ce2690ba476fe2210a8bb419d1311a8349745

**Comment by af** [comment]
Ah sorry, looks like I forgot to push the 3.1.0 tag. You should still be able to install 3.1 from npm, or does your deployment rely on github releases somehow?

**Comment by af** [comment]
Oh wait, that commit was after 3.1, sorry :)

I have a couple of things I want to look into, but should be able to publish a new release within the hour

**Comment by af** [comment]
v3.1.1 just released 🎉

**Comment by grempe** [comment]
Perfect. And my warnings are gone. Thank you for the quick response.
