### ISSUE TITLE
Feature request: Allow prefixing env variables.

### ISSUE THREAD

**Issue by juanjoLenero** [af/envalid#42]
Would it be possible to specify a prefix when cleaning an environment?
```js
const env = envalid.cleanEnv(process.env, {
    API_KEY:            str(),
    ADMIN_EMAIL:        email({ default: 'admin@example.com' }),
    EMAIL_CONFIG_JSON:  json({ desc: 'Additional email parameters' })
}, {prefix: 'MY_APP_NAME'});

env.API_KEY; // Returns the value present at real env variable MY_APP_NAME_API_KEY.
```
My use case is for my dev environment where I run multiple apps and some of the more common env variables clash, less commonly I also have some multi-app deployments.

A current valid solution is to just specify the APP_NAME prefix in all the vars:
```js
const env = envalid.cleanEnv(process.env, {
    MY_APP_NAME_API_KEY:            str(),
    MY_APP_NAME_ADMIN_EMAIL:        email({ default: 'admin@example.com' }),
    MY_APP_NAME_EMAIL_CONFIG_JSON:  json({ desc: 'Additional email parameters' })
});

env.MY_APP_NAME_EMAIL_CONFIG_JSON;
```
This works just fine, but it's a little verbose. I could also use a transformer and remove the prefix after all the variables are loaded.

**Comment by af** [comment]
Hi,

I think the `transformer` option will let you do what you want in a pretty clean way. The readme doesn't really have much info on it anymore, but you can see more context in the PR where it was introduced: https://github.com/af/envalid/pull/15/files

Closing this issue, but let me know if that doesn't solve your issue and we can re-open or discuss further

**Comment by juanjoLenero** [comment]
👍  It definitely solves it, sorry about that, I initially skipped the transformer portion of the documentation.
