### ISSUE TITLE
Strict mode: suggest solutions when throwing errors

### ISSUE THREAD

**Issue by af** [af/envalid#45]
* If an env var was accessed that's not in the schema, but is in process.env, we can suggest adding a validator for that var

* If an accessed env var was not in the validated object, but a similar one was (ie. the error was likely a typo), we can suggest the similar env var name. We don't have to anything fancy like calculating the levenshtein distance; for now could just check if:
  1) The length of name A is within 1 of name B
  2) The first N chars are the same between A and B

**Comment by SimenB** [comment]
I like this idea!

>We don't have to anything fancy like calculating the levenshtein distance;

Isn't using levenshtein distance almost easier than something more manual, as it's just a dependency away?

**Comment by SimenB** [comment]
PR submitted: #50
