### ISSUE TITLE
What are the breaking changes with version 4.x?

### ISSUE THREAD

**Issue by rmehner** [af/envalid#63]
Hey there,

I see that you've pushed out a new envalid version 4.x. We currently depend on 3.x and wonder what the breaking changes are for that new major version and what we need to do to migrate to that version. So far I can't really find anything and there's also no changelog or release notes on the GitHub release.

Would be super nice if you could clarify, so we can start migrating :)

Thank you so much for all you work so far and have a great day!

**Comment by SimenB** [comment]
There's a breaking change if you use `strict mode`. Details in the readme: https://github.com/af/envalid/blob/937f13d8babc576e2a3215280ffbb7c71486c1b1/README.md#strict-mode

We should just add a changelog...

**Comment by rmehner** [comment]
Thank you for the clarification @SimenB!

Changelog would be super nice 👍

**Comment by af** [comment]
Sorry about this @rmehner, I meant to put the change data on the github Release but it slipped my mind! I'll try and do that today. I may even write a blog post with some usage examples. As Simen mentioned the strict mode change is the only breaking change

**Comment by rmehner** [comment]
No worries @af, things like that happen :)

**Comment by af** [comment]
[The releases page](https://github.com/af/envalid/releases) is now updated. Thanks for the reminder!
