### ISSUE TITLE
Suggestion: Rename 'isDev' to 'isDevelopment'?

### ISSUE THREAD

**Issue by rfgamaral** [af/envalid#68]
In the README:

```javascript
// Envalid parses NODE_ENV automatically, and provides the following
// shortcut (boolean) properties for checking its value:
env.isProduction    // true if NODE_ENV === 'production'
env.isTest          // true if NODE_ENV === 'test'
env.isDev           // true if NODE_ENV === 'development'
```

`isDev` is the only one that doesn't match the value from `NODE_ENV`.

For consistency I'm suggestion the `isDev` property to be renamed to `isDevelopment`. I understand if you are opinionated about this and don't want to change it. It's just a suggestion :)

**Comment by SimenB** [comment]
I think that makes sense. Hasn't been too long since I was confused about it: https://github.com/af/envalid/pull/66

**Comment by rfgamaral** [comment]
Let me know if you'd rather I open a merge request :)

**Comment by af** [comment]
Personally I like that `isDev` is shorter, and has no loss of readability. However, the NODE_ENV convention is `'development'` so I can see how this would be confusing. Maybe we should support both?

**Comment by SimenB** [comment]
It should either be `isDev` & `isProd` or `isDevelopment` & `isProduction`. Or all of them, of course 🙂 But having one short and one long is confusing

**Comment by rfgamaral** [comment]
I know most people prefer shorter naming but my personal opinion is that this is code, and it should be as readable and as clear as possible in conveying it's meaning. Thus my vote goes for `isDevelopment` and `isProduction`.

Also, it always look weird to have `isDev`, `isProd` and `isTest` (although less used). Two of them are diminutives, the other is the exact word. Again, no consistency.

Supporting all of them is the alternative and I'm not sure what to think of that. If it was my package, my code base, I would prefer to just support one mode, the longer one. But that's just me. In the end, it's your call :)

**Comment by af** [comment]
We already support `isDev`, and removing that would require a major version bump for what is (IMO) a very minor feature. I don't think the migration would be worth upgrading for most people. So I think removing `isDev` is out.

I'm ok with adding an `isDevelopment` alias (and `isProd` to prevent things like #66). Having the duplicate properties is a minor annoyance but if it makes the library more convenient for folks I think it's worth it.

**Comment by SimenB** [comment]
My vote is adding both `isDevelopment` and `isProd` now so all is supported, and whenever the next major version comes out, remove the short ones. Not worth a major at this point, though

**Comment by rfgamaral** [comment]
Awesome. Thank guys.
