### ISSUE TITLE
Why limiting NODE_ENV to `development,test,production` ?

### ISSUE THREAD

**Issue by yhjor** [af/envalid#73]
Currently, I am using `up` for the serverless deployment of my node.js project.

There are three predefined stage variables from `up`:
  • development
  • staging
  • production

So I cannot assign a stage variable like `test` or whatever.

Here is the error I received: `EnvError: Value "staging" not in choices [development,test,production]`.

I think it is quite normal to use `staging` in NODE_ENV, is it possible to make the NODE_ENV flexible to cater this kind of usage?

**Comment by SimenB** [comment]
You can pass in your own `NODE_ENV` to `cleanEnv`, see https://github.com/af/envalid/blob/f59bb995f63de022f88012baea3279f5e360d98c/index.js#L78

**Comment by juanjoLenero** [comment]
Just got bit by this as well, would you be willing to (accept a pr to) add a notice about this somewhere in the readme?

**Comment by af** [comment]
@juanjoLenero Yes, adding it to the readme is a good idea! Would love to see a PR for this, thanks

**Comment by guy-shahine** [comment]
How about we support `staging` and isStaging part of the default environments?
