### ISSUE TITLE
Suggest making strict mode more configurable

### ISSUE THREAD

**Issue by n1ru4l** [af/envalid#74]
There are some libraries that check if an object is a Promise. Accessing the .then property causes an error 😅

Would be awesome to only use the "remove additional environment variables" option or maybe to allow checking for ".then" method or maybe there is a better way to test the object in the package ?

**Comment by af** [comment]
Ah I see, so a library is checking for `.then()` on the env object? We've had to work around similar checks to allow `console.log` to work with strict mode env objects. Could you try adding `'then'` to the `inspectables` array in `strictProxy.js`, and see if that fixes the issue for you with this library? If that works we should be able to add this small change to one of the next releases.

**Comment by SimenB** [comment]
#76
