### ISSUE TITLE
Change env: any to env: NodeJS.ProcessEnv

### ISSUE THREAD

**Issue by neezer** [af/envalid#82]
NOTE: This is a [continuation to this disucssion.](https://github.com/af/envalid/pull/81#pullrequestreview-118245743)

I propose changing the type of `env`/`environment` ([1](https://github.com/af/envalid/blob/master/envalid.d.ts#L49), [2](https://github.com/af/envalid/blob/master/envalid.d.ts#L68), [3](https://github.com/af/envalid/blob/master/envalid.d.ts#L91), [4](https://github.com/af/envalid/blob/master/envalid.d.ts#L102)) from `any` to [`NodeJS.ProcessEnv`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/index.d.ts#L675-L677).

As I see it, this library exists to do one thing: easily parse external environment variables.

> Envalid is a small library for validating and accessing environment variables in Node.js

This library does not aim to be [a generic object schema validator](https://github.com/hapijs/joi).

So I believe the env input object to `cleanEnv` and associated functions should expect `env`/`environment` to act exactly like—or as close as possible to—the actual object that will be passed in: `process.env`.

- This change would not affect the tests as they are currently written, since the tests are not using TypeScript.
- TS developers can work with a more rigidly defined object type.
- Doesn't affect JS developers—as the code is written right now.

Implementation of this proposal would introduce breaking behavior for TS users who are not already using an argument that satisfies `NodeJS.ProcessEnv` to `cleanEnv` and associated functions.

JS users should be unaffected.

---

I'd be happy to toss up a PR with the proposed change if y'all want to see it in action.

**Comment by af** [comment]
I'm +1 for this, @SimenB ?

**Comment by SimenB** [comment]
I don't use TS, so I don't really care either way, to be honest 😛 I do think supporting the use of `cleanEnv({PORT: 8080})` is useful, but maybe type correctness is more useful?

**Comment by neezer** [comment]
> I do think supporting the use of `cleanEnv({PORT: 8080})` is useful

This is the distinction I draw between parsing environment variables and validating generic object schemas. Since you've provided a hard-coded value of `8080`, I'd argue that you're no longer parsing environment variables.

From the [The Twelve-Factor App](https://12factor.net/config):

> Apps sometimes store config as constants in the code. This is a violation of twelve-factor, which requires strict separation of config from code. Config varies substantially across deploys, code does not.

If you want a generic object validator that asserts that a property is `port`-like, then that could be extracted and shipped as its own module (which envalid could consume), but that should be outside the scope of `cleanEnv` IMO.

**Comment by af** [comment]
I agree, the focus of this lib is specifically for env var validation. This issue gives a very well-reasoned explanation why this is a worthwhile change, and shouldn't disrupt the existing tests. I'd be happy to merge a PR for this 👍
