### ISSUE TITLE
Adding Typescript definition file to @types  repo? 

### ISSUE THREAD

**Issue by sjmcdowall** [af/envalid#84]
Just curious as to why your lovely Typescript d.ts file definition isn't in @types/envalid  ??

**Comment by af** [comment]
Hi, I'm not super familiar with Typescript (the envalid definitions are the work of several other contributors). What's the benefit to having the definitions in that repo, rather than here?

**Comment by sjmcdowall** [comment]
@af -- Basically it's sort of now standard for TS programmers -- when they import a new module to try to do a yarn add --dev @types/module  to bring in the TS definition file.. it's second nature and if you look at the @types repo there are 1000's of TS definition files there from all sorts of things.

Having it here means someone needs to find it -- and then add it to their actual source tree somewhere and point tsconfig to it .. and .. not just have it in the devDependencies (where it's needed). 

So I really think having envalid make a @types/envalid  contribution would be great.  I could give it a whirl (never added anything to @types myself) if that's ok?

**Comment by af** [comment]
Sure go for it! If it makes it easier for people to use the library, sounds great to me.

It seems strange to me that Typescript wouldn't also look in the package's repo for type definitions, though 🤷‍♂️

**Comment by sjmcdowall** [comment]
I was just thinking the same thing actually .. I'm going to explore that and maybe my lack of TS knowledge has me doing something wrong in my tscofnig!  :)

**Comment by af** [comment]
👍  Closing this and looking forward to seeing the definitions added to @types

**Comment by sjmcdowall** [comment]
Your going to be disappointed because -- after some digging and checking -- it's not needed -- tslint does indeed (with a proper config) look at the node module for adefinition .. doh!  Sooooo .. Nevermind ... nothing to see here.. move along :)

**Comment by af** [comment]
Oh great, thanks for looking into that, it's good to know 👍
