### ISSUE TITLE
not failing when env variable not present

### ISSUE THREAD

**Issue by veeramarni** [af/envalid#86]
When we don't define the `NODE_ENV`, it is still picking the default value of `CONNECTION_ID`. Was it suppose to errored when `CONNECTION_ID` not defined in the environment?
```
export const config = envalid.cleanEnv(process.env, {
    NODE_ENV: str({ default: 'production', choices: ['production', 'staging', 'development', 'test'] }),
    CONNECTION_ID: str({ devDefault: 'CONNECTION_ID' }),
});
```

**Comment by af** [comment]
My guess is that because you're setting your own `NODE_ENV` validator, the `devDefault` logic might be confused here. Does it work as expected if you remove the `NODE_ENV` key from your cleanEnv() call?

**Comment by af** [comment]
Closing until the info above is provided

**Comment by veeramarni** [comment]
@af yes it works fine without `NODE_ENV` but based on my understanding it should work when setting `NODE_ENV`.

**Comment by veeramarni** [comment]
@af, basically found out that `default: 'production'` in the `NODE_ENV` validator is not working. But when i set `NODE_ENV=production`externally  it was working as expected.

**Comment by af** [comment]
Hmm, yeah, `NODE_ENV` is treated specially by envalid and it's probably causing this side-effect unfortunately. Since it looks like you only have the custom validator there in order to accept a `'staging'` value, maybe we could have a `extraNodeEnvValues` option that lets you provide other valid values for NOD_ENV.

**Comment by veeramarni** [comment]
@af Did you plan to add `extranodeEnvValues` so we add some additional environments values such as `staging`?
