### ISSUE TITLE
Injecting additional values into an existing env

### ISSUE THREAD

**Issue by kachkaev** [af/envalid#88]
Hi 👋 

I have a Node.js project with a few scripts (entrypoints). Some of them require additional parameters like auth tokens etc. and I would like to extend my env object inside some of the actions. This is not the same as https://github.com/af/envalid/issues/78 because the presence of extra values depends on the code logic rather than the values certain env variables have. An example:

```js
// config.ts
import * as envalid from "envalid";

export const env = envalid.cleanEnv(process.env, {
  SHARED_THING: envalid.str({
    default: "this variable needs to present in all scripts",
  }),
}, { strict: true });
```

```js
// peculiarTask.ts

import { env } from './config';

const extendedEnv = envalid.cleanEnv(env, {
  EXTRA_THING: envalid.str({
    default: "this variable should only be cleaned inside peculiarTask.ts",
  }),
});
```

There are a couple of problems at the moment:

* Using `{ strict: true }` to get `extendedEnv` clears out all variables that used to exist in env.
* Even when there is no `{ strict: true }` in the second case,  TypeScript autocompletion for `extendedEnv.SHARED_THING` does not work.

What improvements could we make here? What do others do in similar cases?

**Comment by SimenB** [comment]
I think I'd merge the specifications (that is, export `SHARED_THING: envalid.str(...` instead of passing it to `cleanEnv`) then do a `cleanEnv` from your entrypoint.

Thoughts?

**Comment by kachkaev** [comment]
I had that in mind as well, so that solution would be something like:

```js
// config.ts
import * as envalid from "envalid";

export const sharedValidators = {
  SHARED_THING: envalid.str({
    default: "this variable needs to present in all scripts",
  }),
};
```

```js
// peculiarTask.ts
import * as envalid from "envalid";
import { sharedValidators } from "./config";

const env = envalid.cleanEnv(process.env, {
  ...sharedValidators,
  EXTRA_THING: envalid.str({
    default: "this variable should only be cleaned inside peculiarTask.ts",
  }),
});
```

This looks rather clean so far, but has two issues:

1.   I have to `import envalid from "envalid"` in every entrypoint and run `const env = envalid.cleanEnv(process.env, sharedValidators, { strict: true })` despite that most of my commands have no peculiar configs.

1.   I can't derive stuff from the shared env in my config.ts such as:

```ts
// config.ts
import * as envalid from "envalid";
import SharedThingManager from "things";
import * as path from "path";

export const env = envalid.cleanEnv(process.env, {
  SHARED_THING: envalid.str({
    default: "this variable needs to present in all scripts",
  }),
}, { strict: true });

// example 1
export const sharedThingManager = new SharedThingManager(env.SHARED_THING);

// example 2
export const resolvedSharedThing = path.resolve(__dirname, env.SHARED_THING);
```

**Comment by af** [comment]
This has been open for a long while and I think the solution of sharing the config (like below) is the best way to go. If there's a more actionable proposal, please open a new issue, going to close this one now

```ts
const env = envalid.cleanEnv(process.env, {
  ...sharedValidators,
  EXTRA_THING: envalid.str({
    default: "this variable should only be cleaned inside peculiarTask.ts",
  }),
});
```
