### ISSUE TITLE
jest test crashes when we have envalid 

### ISSUE THREAD

**Issue by veeramarni** [af/envalid#89]
Not sure if this issue needs to be posted here as the issue happens only when we run `jest` tests. Wondering if anyone has this issue before?

```
cmd: 'cross-env NODE_ENV=test ENV_FILE=config/test/test.env jest "service"'


```

Error
--
```
13 verbose stack Error:  test: `cross-env NODE_ENV=test ENV_FILE=config/test/test.env jest "service"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

Versions:
--
Darwin 15.6.0
node v8.12.0
npm  v6.4.1

**Comment by af** [comment]
I can't reproduce this either, and it's strange that envalid isn't in the traceback you posted. The only things I can suggest to try are removing `NODE_ENV=test` from your command, or removing the `ENV_FILE` var and seeing if the error goes away

**Comment by orditeck** [comment]
[The default reporter exits the node process after outputting the error](https://github.com/af/envalid/blob/a039d3b9af2f1c20f3ca90b1b0375eae24da2189/src/reporter.js#L38) so that would be it.
