### ISSUE TITLE
Are all dependencies needed?

### ISSUE THREAD

**Issue by shawnmclean** [af/envalid#99]
I'm looking into using this on the front-end as opposed to the `env-var` lib due to the ability to override the container (process.env). But this is almost 20x the size. Bundlephobia shows this breakdown: https://bundlephobia.com/result?p=envalid@4.2.2

Or maybe a better question would be is if this lib is suited  for client-side?

**Comment by af** [comment]
Hi,

envalid is intended primarily for server side use, so historically limiting bundle size has not been a focus. I'm not sure there's anything preventing you from using it client-side though.

The bundle breakdown you posted is interesting as it looks like ~60% of that bundle size comes from the `chalk` dependency. I'd definitely accept a PR that replaces `chalk` with something smaller if that ends up being the only blocker for client-side use.

Going to close this issue as I think that answers your question, but feel free to keep the discussion going.
